"""initial schema

Revision ID: defb273941e1
Revises: 
Create Date: 2026-08-20 22:17:37.122548
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

revision: str = 'defb273941e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logistics_nodes',
    sa.Column('node_code', sa.String(length=32), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_load', sa.Integer(), nullable=False),
    sa.Column('operating_status', sa.String(length=32), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # idx_logistics_nodes_geog is intentionally not created here: GeoAlchemy2's
    # Geography column type (spatial_index=True by default) attaches a DDL
    # event that creates/drops this GIST index automatically alongside the
    # table itself. An explicit op.create_index here would duplicate it.
    op.create_index(op.f('ix_logistics_nodes_city'), 'logistics_nodes', ['city'], unique=False)
    op.create_index(op.f('ix_logistics_nodes_node_code'), 'logistics_nodes', ['node_code'], unique=True)
    op.create_index(op.f('ix_logistics_nodes_node_type'), 'logistics_nodes', ['node_type'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('prediction_type', sa.String(length=48), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('input_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_created_at'), 'ml_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ml_predictions_entity_id'), 'ml_predictions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_model_name'), 'ml_predictions', ['model_name'], unique=False)
    op.create_index(op.f('ix_ml_predictions_prediction_type'), 'ml_predictions', ['prediction_type'], unique=False)
    op.create_table('logistics_edges',
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('destination_node_id', sa.UUID(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('estimated_travel_time', sa.Integer(), nullable=False),
    sa.Column('current_travel_time', sa.Integer(), nullable=False),
    sa.Column('road_type', sa.String(length=32), nullable=False),
    sa.Column('congestion_level', sa.Float(), nullable=False),
    sa.Column('route_status', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('active_package_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_node_id'], ['logistics_nodes.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['logistics_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistics_edges_destination_node_id'), 'logistics_edges', ['destination_node_id'], unique=False)
    op.create_index(op.f('ix_logistics_edges_source_node_id'), 'logistics_edges', ['source_node_id'], unique=False)
    op.create_table('merchants',
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('pickup_node_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pickup_node_id'], ['logistics_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('registration_number', sa.String(length=32), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('current_node_id', sa.UUID(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_node_id'], ['logistics_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('order_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_merchant_id'), 'orders', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('riders',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_latitude', sa.Float(), nullable=True),
    sa.Column('current_longitude', sa.Float(), nullable=True),
    sa.Column('current_node_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_node_id'], ['logistics_nodes.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_events',
    sa.Column('edge_id', sa.UUID(), nullable=False),
    sa.Column('congestion_level', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('route_status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['logistics_edges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_events_edge_id'), 'route_events', ['edge_id'], unique=False)
    op.create_index(op.f('ix_route_events_recorded_at'), 'route_events', ['recorded_at'], unique=False)
    op.create_table('vehicle_locations',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_locations_recorded_at'), 'vehicle_locations', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_vehicle_locations_vehicle_id'), 'vehicle_locations', ['vehicle_id'], unique=False)
    op.create_table('packages',
    sa.Column('tracking_number', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('package_type', sa.String(length=32), nullable=False),
    sa.Column('package_weight', sa.Float(), nullable=False),
    sa.Column('package_volume', sa.Float(), nullable=True),
    sa.Column('declared_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_type', sa.String(length=16), nullable=False),
    sa.Column('delivery_type', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('current_node_id', sa.UUID(), nullable=True),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('destination_node_id', sa.UUID(), nullable=False),
    sa.Column('assigned_rider_id', sa.UUID(), nullable=True),
    sa.Column('assigned_vehicle_id', sa.UUID(), nullable=True),
    sa.Column('expected_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_rider_id'], ['riders.id'], ),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['current_node_id'], ['logistics_nodes.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['destination_node_id'], ['logistics_nodes.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['logistics_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_current_status'), 'packages', ['current_status'], unique=False)
    op.create_index(op.f('ix_packages_customer_id'), 'packages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_packages_merchant_id'), 'packages', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_packages_order_id'), 'packages', ['order_id'], unique=False)
    op.create_index(op.f('ix_packages_tracking_number'), 'packages', ['tracking_number'], unique=True)
    op.create_table('delivery_attempts',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('rider_id', sa.UUID(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_attempts_package_id'), 'delivery_attempts', ['package_id'], unique=False)
    op.create_table('package_events',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=True),
    sa.Column('rider_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['logistics_nodes.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_events_created_at'), 'package_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_package_events_event_type'), 'package_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_package_events_package_id'), 'package_events', ['package_id'], unique=False)
    op.create_index(op.f('ix_package_events_timestamp'), 'package_events', ['timestamp'], unique=False)
    op.create_table('package_items',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_items_package_id'), 'package_items', ['package_id'], unique=False)
    op.create_table('routes',
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('node_sequence', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('edge_sequence', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_total_time', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_package_id'), 'routes', ['package_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_package_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_package_items_package_id'), table_name='package_items')
    op.drop_table('package_items')
    op.drop_index(op.f('ix_package_events_timestamp'), table_name='package_events')
    op.drop_index(op.f('ix_package_events_package_id'), table_name='package_events')
    op.drop_index(op.f('ix_package_events_event_type'), table_name='package_events')
    op.drop_index(op.f('ix_package_events_created_at'), table_name='package_events')
    op.drop_table('package_events')
    op.drop_index(op.f('ix_delivery_attempts_package_id'), table_name='delivery_attempts')
    op.drop_table('delivery_attempts')
    op.drop_index(op.f('ix_packages_tracking_number'), table_name='packages')
    op.drop_index(op.f('ix_packages_order_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_merchant_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_customer_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_current_status'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_vehicle_locations_vehicle_id'), table_name='vehicle_locations')
    op.drop_index(op.f('ix_vehicle_locations_recorded_at'), table_name='vehicle_locations')
    op.drop_table('vehicle_locations')
    op.drop_index(op.f('ix_route_events_recorded_at'), table_name='route_events')
    op.drop_index(op.f('ix_route_events_edge_id'), table_name='route_events')
    op.drop_table('route_events')
    op.drop_table('riders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_merchant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('vehicles')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_logistics_edges_source_node_id'), table_name='logistics_edges')
    op.drop_index(op.f('ix_logistics_edges_destination_node_id'), table_name='logistics_edges')
    op.drop_table('logistics_edges')
    op.drop_index(op.f('ix_ml_predictions_prediction_type'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_model_name'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_entity_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_created_at'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_logistics_nodes_node_type'), table_name='logistics_nodes')
    op.drop_index(op.f('ix_logistics_nodes_node_code'), table_name='logistics_nodes')
    op.drop_index(op.f('ix_logistics_nodes_city'), table_name='logistics_nodes')
    # idx_logistics_nodes_geog is dropped automatically by GeoAlchemy2's DDL
    # event when the table itself is dropped below — see the matching note
    # in upgrade().
    op.drop_table('logistics_nodes')
    op.drop_table('customers')
    # ### end Alembic commands ###
