"""Set every corridor's length to the road distance, not the straight line.

`seed_database.py` computed `distance_km` with a haversine between the two
nodes. A truck does not fly: Dhaka to Chattogram is 218 km as the crow flies
and 259 km by road, so every derived figure that multiplies by distance —
line-haul cost per parcel-km, estimated travel time, the cost-per-corridor
tables on the Network page — was understated by roughly a fifth.

The road geometry generated by `frontend/scripts/prep-roads.mjs` already holds
the real length of each corridor, so this reads it rather than calling a
routing service again. Travel times are rescaled by the same ratio, which
preserves whatever congestion has done to `current_travel_time`.

Idempotent. Run from backend/:
    cd backend && ../venv/Scripts/python.exe ../scripts/refresh_edge_distances.py [--dry-run]
"""
import asyncio
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

from sqlalchemy import select

from app.core.database import AsyncSessionLocal, engine
from app.models.edge import LogisticsEdge
from app.models.node import LogisticsNode
from app.services.road_geometry import get_road_geometry

#: Below this the difference is rounding, not a correction worth writing.
MIN_CHANGE_KM = 0.1


async def main(dry_run: bool) -> None:
    roads = get_road_geometry()
    if not roads.by_edge:
        raise SystemExit(
            "No road geometry loaded. Run `node scripts/prep-roads.mjs` from frontend/ first."
        )

    async with AsyncSessionLocal() as session:
        nodes = {n.id: n for n in (await session.execute(select(LogisticsNode))).scalars().all()}
        edges = list((await session.execute(select(LogisticsEdge))).scalars().all())

        changed = 0
        missing = 0
        total_before = 0.0
        total_after = 0.0

        for e in edges:
            src, dst = nodes.get(e.source_node_id), nodes.get(e.destination_node_id)
            if src is None or dst is None:
                continue
            variants = roads.variants(src.longitude, src.latitude, dst.longitude, dst.latitude)
            if not variants:
                missing += 1
                continue

            road_km = round(variants[0].length_m / 1000, 1)
            total_before += e.distance_km
            total_after += road_km
            if abs(road_km - e.distance_km) < MIN_CHANGE_KM or e.distance_km <= 0:
                continue

            ratio = road_km / e.distance_km
            new_est = max(5, round(e.estimated_travel_time * ratio))
            new_cur = max(5, round(e.current_travel_time * ratio))
            print(
                f"  {src.city:12s} -> {dst.city:12s} "
                f"{e.distance_km:7.1f} -> {road_km:7.1f} km   "
                f"{e.estimated_travel_time:4d} -> {new_est:4d} min"
            )
            changed += 1
            if not dry_run:
                e.distance_km = road_km
                e.estimated_travel_time = new_est
                e.current_travel_time = new_cur

        if not dry_run:
            await session.commit()

        print(
            f"\n{len(edges)} edges · {changed} corrected · {missing} with no geometry\n"
            f"network length {total_before:,.0f} km straight-line -> {total_after:,.0f} km by road "
            f"({(total_after / total_before - 1) * 100:+.1f}%)"
        )

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main("--dry-run" in sys.argv))
